name: 'ngrok-macos'

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode'
        required: false
        default: 'ngrok'

jobs:
  ssh-debug:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Choose mode ngrok (macos)
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          set -x
          MODE=${{ github.event.inputs.mode }}
          bash ./${MODE}2actions.sh
        shell: bash

      - name: Sleep
        run: sleep 6h
